# Generated by Django 4.2.10 on 2025-09-16 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school_management', '0004_parent_eleve_parents'),
    ]

    operations = [
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('contenu', models.TextField(verbose_name='Contenu')),
                ('type_communication', models.CharField(choices=[('INFO', 'Information générale'), ('URGENT', 'Urgent'), ('EVENEMENT', 'Événement'), ('RAPPEL', 'Rappel'), ('CONSEIL', 'Conseil')], default='INFO', max_length=20, verbose_name='Type')),
                ('priorite', models.CharField(choices=[('BASSE', 'Basse'), ('NORMALE', 'Normale'), ('HAUTE', 'Haute'), ('URGENTE', 'Urgente')], default='NORMALE', max_length=20, verbose_name='Priorité')),
                ('destinataires', models.CharField(choices=[('TOUS', 'Tous les utilisateurs'), ('PARENTS', 'Parents uniquement'), ('ELEVES', 'Élèves uniquement'), ('PROFESSEURS', 'Professeurs uniquement'), ('ADMINS', 'Administrateurs uniquement'), ('CLASSE', 'Classe spécifique')], default='TOUS', max_length=20, verbose_name='Destinataires')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('date_publication', models.DateTimeField(blank=True, null=True, verbose_name='Date de publication')),
                ('date_expiration', models.DateTimeField(blank=True, null=True, verbose_name="Date d'expiration")),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('piece_jointe', models.FileField(blank=True, null=True, upload_to='communications/', verbose_name='Pièce jointe')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('classe_cible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school_management.classe', verbose_name='Classe cible')),
            ],
            options={
                'verbose_name': 'Communication',
                'verbose_name_plural': 'Communications',
                'ordering': ['-date_creation'],
            },
        ),
    ]
