# Generated by Django 4.2.10 on 2025-09-16 13:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school_management', '0005_communication'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='prof_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes_principales', to='school_management.professeur'),
        ),
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_scolaire', models.CharField(default='2024-2025', max_length=9)),
                ('trimestre', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_ATTENTE', 'En attente de validation'), ('VALIDE', 'Validé'), ('ARCHIVE', 'Archivé')], default='BROUILLON', max_length=20)),
                ('moyenne_generale', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('rang', models.PositiveIntegerField(blank=True, null=True)),
                ('appreciation_generale', models.TextField(blank=True)),
                ('appreciation_prof_principal', models.TextField(blank=True)),
                ('effectif_classe', models.PositiveIntegerField(blank=True, null=True)),
                ('moyenne_classe', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins', to='school_management.classe')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulletins_crees', to=settings.AUTH_USER_MODEL)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins', to='school_management.eleve')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulletins_valides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bulletin',
                'verbose_name_plural': 'Bulletins',
                'ordering': ['-trimestre', 'eleve__user__last_name'],
                'unique_together': {('eleve', 'annee_scolaire', 'trimestre')},
            },
        ),
        migrations.CreateModel(
            name='NoteBulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moyenne_matiere', models.DecimalField(decimal_places=2, max_digits=4)),
                ('coefficient', models.DecimalField(decimal_places=1, max_digits=3)),
                ('appreciation', models.TextField(blank=True)),
                ('bulletin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_detaillees', to='school_management.bulletin')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_management.matiere')),
            ],
            options={
                'verbose_name': 'Note de bulletin',
                'verbose_name_plural': 'Notes de bulletin',
                'ordering': ['matiere__nom'],
                'unique_together': {('bulletin', 'matiere')},
            },
        ),
    ]
