# Generated by Django 4.2.10 on 2025-09-16 20:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school_management', '0007_evaluation_annee_scolaire_evaluation_trimestre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creneau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('LUNDI', 'Lundi'), ('MARDI', 'Mardi'), ('MERCREDI', 'Mercredi'), ('JEUDI', 'Jeudi'), ('VENDREDI', 'Vendredi'), ('SAMEDI', 'Samedi')], max_length=10)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('duree_minutes', models.PositiveIntegerField(default=55)),
                ('pause', models.BooleanField(default=False, help_text='Créneau de pause')),
            ],
            options={
                'verbose_name': 'Créneau',
                'verbose_name_plural': 'Créneaux',
                'ordering': ['jour', 'heure_debut'],
                'unique_together': {('jour', 'heure_debut')},
            },
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('numero', models.CharField(max_length=10, unique=True)),
                ('capacite', models.PositiveIntegerField(default=30)),
                ('type_salle', models.CharField(choices=[('COURS', 'Salle de cours'), ('LABO', 'Laboratoire'), ('INFO', 'Salle informatique'), ('SPORT', 'Salle de sport'), ('BIBLIO', 'Bibliothèque'), ('AUDITORIUM', 'Auditorium'), ('AUTRE', 'Autre')], default='COURS', max_length=20)),
                ('equipements', models.TextField(blank=True, help_text='Équipements disponibles')),
                ('accessible_handicap', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Salle',
                'verbose_name_plural': 'Salles',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='ReservationSalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('statut', models.CharField(choices=[('DEMANDE', 'Demande'), ('CONFIRME', 'Confirmé'), ('REFUSE', 'Refusé'), ('ANNULE', 'Annulé')], default='DEMANDE', max_length=20)),
                ('motif', models.CharField(blank=True, max_length=200)),
                ('nombre_personnes', models.PositiveIntegerField(default=1)),
                ('equipements_demandes', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('commentaire_validation', models.TextField(blank=True)),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='school_management.salle')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_validees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Réservation de salle',
                'verbose_name_plural': 'Réservations de salles',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='EvenementCalendrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('type_evenement', models.CharField(choices=[('VACANCES', 'Vacances'), ('JOUR_FERIE', 'Jour férié'), ('EXAMEN', 'Examen'), ('REUNION', 'Réunion'), ('SORTIE', 'Sortie scolaire'), ('EVENEMENT', 'Événement'), ('FORMATION', 'Formation'), ('AUTRE', 'Autre')], max_length=20)),
                ('priorite', models.CharField(choices=[('BASSE', 'Basse'), ('NORMALE', 'Normale'), ('HAUTE', 'Haute'), ('URGENTE', 'Urgente')], default='NORMALE', max_length=20)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('jour_entier', models.BooleanField(default=False)),
                ('annee_scolaire', models.CharField(default='2024-2025', max_length=9)),
                ('lieu', models.CharField(blank=True, max_length=200)),
                ('couleur', models.CharField(default='#007bff', help_text='Couleur hexadécimale', max_length=7)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('classes_concernees', models.ManyToManyField(blank=True, related_name='evenements', to='school_management.classe')),
                ('organisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenements_organises', to=settings.AUTH_USER_MODEL)),
                ('professeurs_concernees', models.ManyToManyField(blank=True, related_name='evenements', to='school_management.professeur')),
            ],
            options={
                'verbose_name': 'Événement calendrier',
                'verbose_name_plural': 'Événements calendrier',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='EmploiDuTemps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_cours', models.CharField(choices=[('COURS', 'Cours normal'), ('TD', 'Travaux dirigés'), ('TP', 'Travaux pratiques'), ('EXAMEN', 'Examen'), ('CONTROLE', 'Contrôle'), ('REUNION', 'Réunion'), ('AUTRE', 'Autre')], default='COURS', max_length=20)),
                ('annee_scolaire', models.CharField(default='2024-2025', max_length=9)),
                ('semestre', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)])),
                ('actif', models.BooleanField(default=True)),
                ('commentaire', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emplois_du_temps', to='school_management.classe')),
                ('creneau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_management.creneau')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_management.matiere')),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_management.professeur')),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_management.salle')),
            ],
            options={
                'verbose_name': 'Emploi du temps',
                'verbose_name_plural': 'Emplois du temps',
                'ordering': ['classe', 'creneau__jour', 'creneau__heure_debut'],
                'unique_together': {('classe', 'creneau', 'annee_scolaire', 'semestre')},
            },
        ),
    ]
