# Generated by Django 4.2.10 on 2025-09-17 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school_management', '0009_conversation_message_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='createur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='conversations_creees', to=settings.AUTH_USER_MODEL),
        ),
    ]
